export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";

export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const ARCHIVE_USER_SUCCESS = "ARCHIVE_USER_SUCCESS";

export const FETCH_BASIC_INFO_REQUEST = "FETCH_BASIC_INFO_REQUEST";
export const FETCH_BASIC_INFO_SUCCESS = "FETCH_BASIC_INFO_SUCCESS";
export const FETCH_BASIC_INFO_FAILURE = "FETCH_BASIC_INFO_FAILURE";

export const UPDATE_BASIC_INFO_REQUEST = "UPDATE_BASIC_INFO_REQUEST";
export const UPDATE_BASIC_INFO_SUCCESS = "UPDATE_BASIC_INFO_SUCCESS";
export const UPDATE_BASIC_INFO_FAILURE = "UPDATE_BASIC_INFO_FAILURE";

export const FETCH_GENERAL_INFO_REQUEST = "FETCH_GENERAL_INFO_REQUEST";
export const FETCH_GENERAL_INFO_SUCCESS = "FETCH_GENERAL_INFO_SUCCESS";
export const FETCH_GENERAL_INFO_FAILURE = "FETCH_GENERAL_INFO_FAILURE";

export const UPDATE_GENERAL_INFO_REQUEST = "UPDATE_GENERAL_INFO_REQUEST";
export const UPDATE_GENERAL_INFO_SUCCESS = "UPDATE_GENERAL_INFO_SUCCESS";
export const UPDATE_GENERAL_INFO_FAILURE = "UPDATE_GENERAL_INFO_FAILURE";

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";