export const FETCH_AGENCIES_REQUEST = "FETCH_AGENCIES_REQUEST";
export const FETCH_AGENCIES_SUCCESS = "FETCH_AGENCIES_SUCCESS";
export const FETCH_AGENCIES_FAILURE = "FETCH_AGENCIES_FAILURE";

export const ADD_AGENCIES_REQUEST = "ADD_AGENCIES_REQUEST";
export const ADD_AGENCIES_SUCCESS = "ADD_AGENCIES_SUCCESS";
export const ADD_AGENCIES_FAILURE = "ADD_AGENCIES_FAILURE";

export const UPDATE_AGENCIES_REQUEST = "UPDATE_AGENCIES_REQUEST";
export const UPDATE_AGENCIES_SUCCESS = "UPDATE_AGENCIES_SUCCESS";
export const UPDATE_AGENCIES_FAILURE = "UPDATE_AGENCIES_FAILURE";

export const ARCHIVE_AGENCIES_SUCCESS = "ARCHIVE_AGENCIES_SUCCESS";
