export const FETCH_TEAMS_REQUEST = "FETCH_TEAMS_REQUEST";
export const FETCH_TEAMS_SUCCESS = "FETCH_TEAMS_SUCCESS";
export const FETCH_TEAMS_FAILURE = "FETCH_TEAMS_FAILURE";

export const ADD_TEAMS_REQUEST = "ADD_TEAMS_REQUEST";
export const ADD_TEAMS_SUCCESS = "ADD_TEAMS_SUCCESS";
export const ADD_TEAMS_FAILURE = "ADD_TEAMS_FAILURE";

export const UPDATE_TEAMS_REQUEST = "UPDATE_TEAMS_REQUEST";
export const UPDATE_TEAMS_SUCCESS = "UPDATE_TEAMS_SUCCESS";
export const UPDATE_TEAMS_FAILURE = "UPDATE_TEAMS_FAILURE";

export const ARCHIVE_TEAMS_SUCCESS = "ARCHIVE_TEAMS_SUCCESS";
